### ISSUE TITLE
refactor DES specific code

### ISSUE THREAD

**Issue by beckermr** [beckermr/desmedser#10]
I had envisioned only a single class for this, but I think Erin is right that this should be split. I think we actually want three classes.

1. MEDSMaker - makes MEDS files from stubby MEDS files w/ the requirement that the only input to this class is the stubby MEDS file itself and that all data be in a standard set of data fields
2. BaseStubbyMEDSMaker - writes stubby MEDS files and defines the standard data fields
3. DESStubbyMEDSMaker - writes DES stubby MEDS files according to data standard

**Comment by esheldon** [comment]
what do you have in mind here?  Should BaseStubbyMEDSMaker be in the meds repo?

**Comment by beckermr** [comment]
The idea is that the StubbyMEDSMaker is basically an example of how to make a stubby MEDS file for the MEDSMaker to process. 

So given this, putting it in the MEDS repo makes total sense to me.

**Comment by beckermr** [comment]
Looks like we passed on this one in favor of only low level utils in the meds repo. Fine by me.

**Comment by esheldon** [comment]
Yeah, I do think there might be an intermediate stage we could refactor to, but what we have is currently sufficient
