### ISSUE TITLE
stage output files

### ISSUE THREAD

**Issue by esheldon** [beckermr/desmedser#15]
Use a StagedOutputFile, but only for the fits.fz file.  Clean up the .fits file

**Comment by beckermr** [comment]
Let's make a TempFile class that can be called us `with ... as ...` to make this robust.

**Comment by esheldon** [comment]
I was just working on that!

On 11/6/15, Matthew R. Becker <notifications@github.com> wrote:
> Let's make a TempFile class that can be called us `with ... as ...` to make
> this robust.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/beckermr/desmedser/issues/15#issuecomment-154492692


-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com
