### ISSUE TITLE
duplicate defaults in row and col offsets - bug prone

### ISSUE THREAD

**Issue by beckermr** [beckermr/desmedser#9]
We should not leave duplicate `row_offset` and `col_offset` defaults in two places. Here

https://github.com/beckermr/desmedser/blob/master/desmedser/medsmaker.py#L44

and here

https://github.com/beckermr/desmedser/blob/master/desmedser/medsmaker.py#L76

This is massively bug prone, since one could be changed and the other not. If that did happen, the bug would be so subtle that it would probably not be noticed for a long time.

**Comment by beckermr** [comment]
actually, this should be put as another column in the image_info table since it is needed to interpret the WCS. If we do that, then we can remove the default setting from the MEDSMaker and just leave it in the DESMEDSMaker

**Comment by esheldon** [comment]
We should make a new data structure holding positions.  It will be an array
with entries

```
dtype=[('row','f8'),
       ('col','f8'),
       ('row_offset','f8'),
       ('col_offset','f8')]
```
These will then get used appropriately.  The bug then is only if the
right one is used at the right time.

**Comment by esheldon** [comment]
Note I refactored out the subtracting and adding of offsets to special methods, which at least reduces the total code where this exists

**Comment by beckermr** [comment]
What is the new data structure for?

**Comment by beckermr** [comment]
Ohh I see. This new data structure has one entry for each object and then things just get added or subtracted back? I think this doesn't make sense in the general case. The offsets are a property of the WCS and image, not of the objects themselves. Imagine a coadd with zero offsets and SE images with 1 offsets. This would be a nightmare, but if the offsets are stored in the image_info table for each image, then they can be pulled appropriately and fed into your methods for adding them and subtracting them.

**Comment by esheldon** [comment]
On 11/3/15, Matthew R. Becker <notifications@github.com> wrote:
> Ohh I see. This new data structure has one entry for each object and then
> things just get added or subtracted back?

No, it has 4 columns.  It keeps a copy of the original row,col which are used
for wcs related things, and the offset subtracted one used for everything
else.

This way we only do the subtraction one time and then just use the right
columns at the right places in the code.

-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by beckermr** [comment]
Still confused then. The offsets are properties of the images and so go with the image and the WCS.

**Comment by esheldon** [comment]
On 11/3/15, Matthew R. Becker <notifications@github.com> wrote:
> Still confused then. The offsets are properties of the images and so go with
> the image and the WCS.

There are times when we want to use the wcs.  We need the original
not-offset positions.

There are times we want the zero offset positions.

Currently we are adding or subtracting offsets all over the place to
get what we want.

So make a temporary structure that has both in it, and use the ones
you want at the place you want rather than adding or subtracting
offsets.

**Comment by beckermr** [comment]
Ohhh. So we make one temporary structure for each image then (so 4xNimagexNobject floats) or do we require the images to all have the same convention?

**Comment by beckermr** [comment]
closing this. we require all images to have the same convention.
